---
- name: Configure Nginx Web Server
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Deploy custom index page
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
